version: '3'

services:
  web:
    build: .
    command: start
    depends_on:
      - 'postgres'
      - 'redis'
    ports:
      - "3000:3000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/}

  redis:
    image: redis:4.0-alpine
    restart: always

  postgres:
    image: postgres:9.6-alpine
    restart: always

  sidekiq:
    build: .
    command: sidekiq
    depends_on:
      - 'postgres'
      - 'redis'
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/}

  cable:
    build: .
    command: cable
    depends_on:
      - 'redis'
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/}
    command: cable
    ports:
      - '28080:28080'

