version: '3'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  redis:
    image: redis:4.0
