version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - db_name=postgres
      - db_host=postgres
      - redis_url=redis://redis:6379/

  redis:
    image: redis:4.0-alpine

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq
    environment:
      - db_name=postgres
      - db_host=postgres
      - redis_url=redis://redis:6379/

