version: '3'

services:
  web:
    build: .
    command: start
    ports:
      - "3000:${API_PORT:-3000}"
    environment:
      - db_name=postgres
      - db_host=postgres
      - redis_url=redis://redis:6379/

  redis:
    image: redis:4.0-alpine

  sidekiq:
    build: .
    command: sidekiq
    depends_on:
      - 'postgres'
      - 'redis'
    environment:
      - db_name=postgres
      - db_host=postgres
      - redis_url=redis://redis:6379/

