version: '3'

services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    depends_on:
      - postgres
    environment:
      - db_name=postgres
      - db_host=postgres

  sidekiq:
    depends_on:
      - 'postgres'
    environment:
      - db_name=postgres
      - db_host=postgres
