branch-defaults:
  aws-setup-docker:
    environment: liveup-api-staging
    group_suffix: null
  feature/aws_streaming:
    environment: liveup-staging
  master:
    environment: liveup-api-prod
    group_suffix: null
  setup/sidekiq-with-docker:
    environment: liveup-second-boris-dev2
environment-defaults:
  liveup-api-prod:
    branch: null
    repository: null
  liveup-api-staging:
    branch: null
    repository: null
  liveup-api-staging-new:
    branch: null
    repository: null
  liveup-second-boris-dev:
    branch: null
    repository: null
  liveup-staging:
    branch: null
    repository: null
global:
  application_name: liveup-api-prod
  branch: null
  default_ec2_keyname: liveup-api
  default_platform: Multi-container Docker 17.12.1-ce (Generic)
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
