development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://redistogo:aff9cc76ddee4104f91bdd34ec257dc6@porgy.redistogo.com:10507/
  url: <%= ENV["REDIS_URL"] || "redis://" %>
