default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USERNAME"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] || "" %>
  host: <%= ENV["DB_HOST"] || "localhost" %>
  port: <%= ENV["DB_PORT"] || 5432 %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || "liveup" %>_dev

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || "liveup" %>_test

production:
  <<: *default
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
