default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV["db_name"] || "postgres" %>
  password:  <%= ENV["db_pass"] || "" %>
  host: <%= ENV["db_host"] || "postgres" %>

development:
  <<: *default
  database: liveup_development

test:
  <<: *default
  database: liveup_test

production:
  <<: *default
  database: liveup_production
