default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: ENV["db_username"] || postgres
  password:
  host: postgres

development:
  <<: *default
  database: liveup_development

test:
  <<: *default
  database: liveup_test

production:
  <<: *default
  database: liveup_production
